/* The following code was generated by JFlex 1.4.3 on 5/25/17 3:01 PM */

package com.duy.pascal.backend.tokenizer;

import com.duy.pascal.backend.exceptions.grouping.GroupingExceptionType;
import com.duy.pascal.backend.exceptions.grouping.StrayCharacterException;
import com.duy.pascal.backend.linenumber.LineInfo;
import com.duy.pascal.backend.pascaltypes.OperatorTypes;
import com.duy.pascal.backend.tokens.CommentToken;
import com.duy.pascal.backend.tokens.EOFToken;
import com.duy.pascal.backend.tokens.GroupingExceptionToken;
import com.duy.pascal.backend.tokens.OperatorToken;
import com.duy.pascal.backend.tokens.Token;
import com.duy.pascal.backend.tokens.WarningToken;
import com.duy.pascal.backend.tokens.WordToken;
import com.duy.pascal.backend.tokens.basic.ArrayToken;
import com.duy.pascal.backend.tokens.basic.AssignmentToken;
import com.duy.pascal.backend.tokens.basic.BreakToken;
import com.duy.pascal.backend.tokens.basic.ColonToken;
import com.duy.pascal.backend.tokens.basic.CommaToken;
import com.duy.pascal.backend.tokens.basic.ConstToken;
import com.duy.pascal.backend.tokens.basic.ContinueToken;
import com.duy.pascal.backend.tokens.basic.DoToken;
import com.duy.pascal.backend.tokens.basic.DotDotToken;
import com.duy.pascal.backend.tokens.basic.DowntoToken;
import com.duy.pascal.backend.tokens.basic.ElseToken;
import com.duy.pascal.backend.tokens.basic.FinalizationToken;
import com.duy.pascal.backend.tokens.basic.ForToken;
import com.duy.pascal.backend.tokens.basic.ForwardToken;
import com.duy.pascal.backend.tokens.basic.FunctionToken;
import com.duy.pascal.backend.tokens.basic.IfToken;
import com.duy.pascal.backend.tokens.basic.ImplementationToken;
import com.duy.pascal.backend.tokens.basic.InitializationToken;
import com.duy.pascal.backend.tokens.basic.InterfaceToken;
import com.duy.pascal.backend.tokens.basic.OfToken;
import com.duy.pascal.backend.tokens.basic.PeriodToken;
import com.duy.pascal.backend.tokens.basic.ProcedureToken;
import com.duy.pascal.backend.tokens.basic.ProgramToken;
import com.duy.pascal.backend.tokens.basic.SemicolonToken;
import com.duy.pascal.backend.tokens.basic.SetToken;
import com.duy.pascal.backend.tokens.basic.ThenToken;
import com.duy.pascal.backend.tokens.basic.ToToken;
import com.duy.pascal.backend.tokens.basic.TypeToken;
import com.duy.pascal.backend.tokens.basic.UsesToken;
import com.duy.pascal.backend.tokens.basic.VarToken;
import com.duy.pascal.backend.tokens.basic.WhileToken;
import com.duy.pascal.backend.tokens.basic.WithToken;
import com.duy.pascal.backend.tokens.closing.EndBracketToken;
import com.duy.pascal.backend.tokens.closing.EndParenToken;
import com.duy.pascal.backend.tokens.closing.EndToken;
import com.duy.pascal.backend.tokens.closing.UntilToken;
import com.duy.pascal.backend.tokens.grouping.BeginEndToken;
import com.duy.pascal.backend.tokens.grouping.BracketedToken;
import com.duy.pascal.backend.tokens.grouping.CaseToken;
import com.duy.pascal.backend.tokens.grouping.ParenthesizedToken;
import com.duy.pascal.backend.tokens.grouping.RecordToken;
import com.duy.pascal.backend.tokens.grouping.RepeatToken;
import com.duy.pascal.backend.tokens.grouping.UnitToken;
import com.duy.pascal.backend.tokens.value.BooleanToken;
import com.duy.pascal.backend.tokens.value.CharacterToken;
import com.duy.pascal.backend.tokens.value.DoubleToken;
import com.duy.pascal.backend.tokens.value.IntegerToken;
import com.duy.pascal.backend.tokens.value.StringToken;
import com.js.interpreter.source_include.ScriptSource;

import java.io.FileNotFoundException;
import java.io.Reader;
import java.util.List;
import java.util.Stack;


/**
 * This class is a scanner generated by
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/25/17 3:01 PM from the specification file
 * <tt>C:/github/pascalnide/libCompiler/src/main/java/com/duy/pascal/backend/tokenizer/Lexer2.flex</tt>
 */
class Lexer {

    /**
     * This character denotes the end of file
     */
    public static final int YYEOF = -1;
    /**
     * lexical states
     */
    public static final int STRINGDONE = 4;
    public static final int STRING = 2;
    public static final int YYINITIAL = 0;
    public static final int STRINGPOUND = 6;
    public static final int INCLUDE_SNGL_QUOTE = 12;
    public static final int INCLUDE = 8;
    public static final int END_INCLUDE = 14;
    public static final int INCLUDE_DBL_QUOTE = 10;
    /**
     * initial size of the lookahead buffer
     */
    private static final int ZZ_BUFFERSIZE = 16384;
    /**
     * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
     * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
     * at the beginning of a line
     * l is of the form l = 2*k, k a non negative integer
     */
    private static final int ZZ_LEXSTATE[] = {
            0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7
    };

    /**
     * Translates characters to character classes
     */
    private static final String ZZ_CMAP_PACKED =
            "\11\0\1\4\1\6\2\0\1\5\22\0\1\66\1\0\1\65\1\3" +
                    "\1\17\2\0\1\64\1\11\1\14\1\12\1\43\1\55\1\44\1\10" +
                    "\1\16\12\1\1\54\1\56\1\36\1\42\1\37\1\0\1\45\1\27" +
                    "\1\57\1\22\1\25\1\26\1\47\1\53\1\35\1\20\1\2\1\60" +
                    "\1\23\1\41\1\21\1\30\1\52\1\2\1\32\1\34\1\31\1\24" +
                    "\1\40\1\50\1\33\1\51\1\61\1\62\1\0\1\63\1\46\1\2" +
                    "\1\0\1\27\1\57\1\22\1\25\1\26\1\47\1\53\1\35\1\20" +
                    "\1\2\1\60\1\23\1\41\1\21\1\30\1\52\1\2\1\32\1\34" +
                    "\1\31\1\24\1\40\1\50\1\33\1\51\1\61\1\13\1\7\1\15" +
                    "\uff82\0";

    /**
     * Translates characters to character classes
     */
    private static final char[] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);
    private static final String ZZ_ACTION_PACKED_0 =
            "\1\0\1\1\6\0\1\2\1\3\1\4\1\2\1\5" +
                    "\1\6\1\7\1\10\1\2\1\11\1\12\14\4\1\13" +
                    "\1\14\2\4\1\15\1\16\1\17\1\20\1\21\3\4" +
                    "\1\22\1\23\1\24\1\4\1\25\1\26\1\27\1\1" +
                    "\1\30\1\31\4\32\1\33\1\34\1\35\1\36\1\5" +
                    "\1\37\1\40\1\41\1\1\1\42\1\43\1\44\1\45" +
                    "\2\46\1\47\1\0\1\50\1\51\5\0\1\52\1\4" +
                    "\1\53\6\4\1\54\4\4\1\55\1\56\1\57\7\4" +
                    "\1\60\1\61\1\62\1\63\1\64\1\65\11\4\1\66" +
                    "\2\4\1\67\1\0\1\70\1\67\2\0\1\71\2\0" +
                    "\1\72\2\0\1\73\3\0\1\72\3\4\1\74\5\4" +
                    "\1\75\1\4\1\76\1\4\1\77\6\4\1\100\1\101" +
                    "\1\60\1\64\1\102\1\103\3\4\1\104\5\4\3\0" +
                    "\1\73\3\0\1\105\2\0\3\4\1\106\2\4\1\107" +
                    "\1\4\1\110\1\4\1\111\1\4\1\112\1\113\1\114" +
                    "\6\4\1\115\5\4\1\0\1\105\2\0\4\4\1\116" +
                    "\1\117\1\4\1\120\4\4\1\121\1\4\1\122\2\4" +
                    "\1\123\1\124\1\72\2\0\4\4\1\125\1\126\1\127" +
                    "\5\4\2\0\6\4\1\130\1\4\1\131\2\0\3\4" +
                    "\1\132\1\4\1\133\1\4\1\0\1\4\1\134\2\4" +
                    "\1\135\10\4\1\136\2\4\1\137\1\140";
    /**
     * Translates DFA states to action switch labels.
     */
    private static final int[] ZZ_ACTION = zzUnpackAction();
    private static final String ZZ_ROWMAP_PACKED_0 =
            "\0\0\0\67\0\156\0\245\0\334\0\u0113\0\u014a\0\u0181" +
                    "\0\u01b8\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302\0\u01b8" +
                    "\0\u0339\0\u01b8\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483" +
                    "\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b" +
                    "\0\u0672\0\u06a9\0\u06e0\0\u01b8\0\u01b8\0\u01b8\0\u01b8\0\u01b8" +
                    "\0\u0717\0\u074e\0\u0785\0\u07bc\0\u01b8\0\u01b8\0\u07f3\0\u01b8" +
                    "\0\u01b8\0\u01b8\0\u082a\0\u01b8\0\u0861\0\u01b8\0\u0898\0\u08cf" +
                    "\0\u0370\0\u01b8\0\u01b8\0\u0906\0\u093d\0\u0974\0\u01b8\0\u093d" +
                    "\0\u093d\0\u09ab\0\u01b8\0\u09e2\0\u01b8\0\u0a19\0\u0a50\0\u0a87" +
                    "\0\u0a50\0\u0abe\0\u025d\0\u01b8\0\u0af5\0\u0b2c\0\u0b63\0\u0b9a" +
                    "\0\u0bd1\0\u0c08\0\u0c3f\0\u0226\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b" +
                    "\0\u0d52\0\u0d89\0\u0dc0\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\u0226" +
                    "\0\u0226\0\u0226\0\u0ed3\0\u0f0a\0\u0f41\0\u0f78\0\u0faf\0\u0fe6" +
                    "\0\u101d\0\u01b8\0\u01b8\0\u01b8\0\u01b8\0\u01b8\0\u01b8\0\u1054" +
                    "\0\u108b\0\u10c2\0\u10f9\0\u1130\0\u1167\0\u119e\0\u11d5\0\u120c" +
                    "\0\u01b8\0\u1243\0\u127a\0\u01b8\0\u12b1\0\u09ab\0\u09ab\0\u0a50" +
                    "\0\u0a87\0\u0abe\0\u12e8\0\u131f\0\u01b8\0\u1356\0\u138d\0\u13c4" +
                    "\0\u13fb\0\u1432\0\u1469\0\u14a0\0\u14d7\0\u150e\0\u1545\0\u0226" +
                    "\0\u157c\0\u15b3\0\u15ea\0\u1621\0\u1658\0\u0226\0\u168f\0\u0226" +
                    "\0\u16c6\0\u0226\0\u16fd\0\u1734\0\u176b\0\u17a2\0\u17d9\0\u1810" +
                    "\0\u0226\0\u0226\0\u0226\0\u0226\0\u0226\0\u0226\0\u1847\0\u187e" +
                    "\0\u18b5\0\u18ec\0\u1923\0\u195a\0\u1991\0\u19c8\0\u19ff\0\u1a36" +
                    "\0\u1a6d\0\u1aa4\0\u1a6d\0\u1adb\0\u13c4\0\u1b12\0\u1356\0\u1b49" +
                    "\0\u1b80\0\u1bb7\0\u1bee\0\u1c25\0\u0226\0\u1c5c\0\u1c93\0\u0226" +
                    "\0\u1cca\0\u0226\0\u1d01\0\u0226\0\u1d38\0\u0226\0\u0226\0\u0226" +
                    "\0\u1d6f\0\u1da6\0\u1ddd\0\u1e14\0\u1e4b\0\u1e82\0\u0226\0\u1eb9" +
                    "\0\u1ef0\0\u1f27\0\u1f5e\0\u1f95\0\u1fcc\0\u1a6d\0\u2003\0\u203a" +
                    "\0\u2071\0\u20a8\0\u20df\0\u2116\0\u0226\0\u0226\0\u214d\0\u0226" +
                    "\0\u2184\0\u21bb\0\u21f2\0\u2229\0\u0226\0\u2260\0\u0226\0\u2297" +
                    "\0\u22ce\0\u0226\0\u0226\0\u13c4\0\u2305\0\u233c\0\u2373\0\u23aa" +
                    "\0\u23e1\0\u2418\0\u0226\0\u0226\0\u0226\0\u244f\0\u2486\0\u24bd" +
                    "\0\u24f4\0\u252b\0\u2562\0\u2599\0\u25d0\0\u2607\0\u263e\0\u2675" +
                    "\0\u26ac\0\u26e3\0\u0226\0\u271a\0\u0226\0\u2751\0\u2788\0\u27bf" +
                    "\0\u27f6\0\u282d\0\u0226\0\u2864\0\u0226\0\u289b\0\u28d2\0\u2909" +
                    "\0\u0226\0\u2940\0\u2977\0\u0226\0\u29ae\0\u29e5\0\u2a1c\0\u2a53" +
                    "\0\u2a8a\0\u2ac1\0\u2af8\0\u2b2f\0\u0226\0\u2b66\0\u2b9d\0\u0226" +
                    "\0\u0226";
    /**
     * Translates a state to a row index in the transition table
     */
    private static final int[] ZZ_ROWMAP = zzUnpackRowMap();
    private static final String ZZ_TRANS_PACKED_0 =
            "\1\11\1\12\1\13\1\14\3\15\1\11\1\16\1\17" +
                    "\1\20\1\21\1\22\1\11\1\23\1\11\1\24\1\25" +
                    "\1\26\1\13\1\27\1\30\1\31\1\32\1\33\1\34" +
                    "\1\35\1\36\1\37\1\13\1\40\1\41\1\42\1\43" +
                    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\13" +
                    "\1\53\1\13\1\54\1\55\1\56\1\57\2\13\1\60" +
                    "\1\61\1\62\1\11\1\15\5\63\2\64\55\63\1\65" +
                    "\2\63\4\66\3\15\2\66\1\67\1\66\1\70\2\66" +
                    "\1\71\45\66\1\72\1\66\1\15\1\73\1\74\65\73" +
                    "\4\75\1\76\2\15\3\75\1\77\1\75\2\77\46\75" +
                    "\1\100\1\101\1\15\5\102\2\103\56\102\1\104\6\102" +
                    "\2\105\55\102\1\106\2\102\12\107\1\110\2\107\1\111" +
                    "\51\107\70\0\1\12\6\0\1\112\57\0\2\13\15\0" +
                    "\16\13\2\0\2\13\5\0\5\13\3\0\3\13\6\0" +
                    "\1\113\71\0\3\15\57\0\1\15\10\0\1\114\70\0" +
                    "\1\115\54\0\12\116\1\0\4\116\1\117\47\116\12\0" +
                    "\1\120\3\0\1\121\51\0\2\13\15\0\1\13\1\122" +
                    "\14\13\2\0\1\13\1\123\5\0\1\124\4\13\3\0" +
                    "\3\13\6\0\2\13\15\0\10\13\1\125\5\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\7\13\1\126\1\127\5\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\1\13\1\130\12\13" +
                    "\1\131\1\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\1\132\7\13\1\133\5\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\1\13\1\134\1\13\1\135\12\13\2\0\2\13\5\0" +
                    "\5\13\3\0\3\13\6\0\2\13\15\0\1\13\1\136" +
                    "\10\13\1\137\3\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\12\13\1\140\3\13\2\0" +
                    "\2\13\5\0\1\141\4\13\3\0\3\13\6\0\2\13" +
                    "\15\0\10\13\1\142\1\13\1\143\2\13\1\144\2\0" +
                    "\2\13\5\0\2\13\1\145\2\13\3\0\3\13\6\0" +
                    "\2\13\15\0\6\13\1\146\7\13\2\0\2\13\5\0" +
                    "\5\13\3\0\3\13\6\0\2\13\15\0\10\13\1\147" +
                    "\5\13\2\0\2\13\5\0\5\13\3\0\3\13\6\0" +
                    "\2\13\15\0\6\13\1\150\6\13\1\151\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\43\0\1\152\1\153\2\0" +
                    "\1\154\62\0\1\155\1\156\2\0\1\157\25\0\2\13" +
                    "\15\0\7\13\1\160\6\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\10\13\1\161\5\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\1\162\3\13\1\163\2\13\1\164\1\165\5\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\1\166\14\13\1\167\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\12\13\1\170\3\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\47\0\1\171" +
                    "\25\0\2\13\15\0\6\13\1\172\3\13\1\173\3\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\5\0\5\63" +
                    "\2\0\55\63\1\0\2\63\64\0\1\174\14\0\1\175" +
                    "\54\0\12\116\1\0\54\116\1\0\1\74\65\0\5\75" +
                    "\2\0\3\75\1\0\1\75\2\0\50\75\1\0\4\75" +
                    "\1\76\2\15\3\75\1\0\1\75\2\0\50\75\1\15" +
                    "\5\102\2\0\65\102\2\0\56\102\1\176\6\102\2\0" +
                    "\55\102\1\177\2\102\12\200\1\201\2\200\1\111\65\200" +
                    "\2\0\51\200\1\0\1\202\65\0\12\203\1\0\4\203" +
                    "\1\204\47\203\15\116\1\205\51\116\12\206\1\207\2\206" +
                    "\1\210\2\206\1\211\46\206\12\212\1\213\54\212\5\121" +
                    "\1\214\1\205\1\0\57\121\1\0\2\13\15\0\1\215" +
                    "\10\13\1\216\4\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\16\13\2\0\2\13\5\0" +
                    "\3\13\1\217\1\13\3\0\3\13\6\0\2\13\15\0" +
                    "\11\13\1\220\4\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\14\13\1\221\1\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\1\13\1\222\14\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\1\223\10\13\1\224\4\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\6\13\1\225\7\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\16\13\2\0\1\226" +
                    "\1\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\16\13\2\0\2\13\5\0\1\13\1\227\3\13\3\0" +
                    "\3\13\6\0\2\13\15\0\5\13\1\230\10\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\14\13\1\231\1\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\5\13\1\232\10\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\12\13\1\233\3\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\4\13\1\234\11\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\6\13\1\235\7\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\16\13\2\0\2\13\5\0" +
                    "\3\13\1\236\1\13\3\0\3\13\6\0\2\13\15\0" +
                    "\2\13\1\237\13\13\2\0\2\13\5\0\3\13\1\240" +
                    "\1\13\3\0\3\13\6\0\2\13\15\0\12\13\1\241" +
                    "\3\13\2\0\2\13\5\0\5\13\3\0\3\13\6\0" +
                    "\2\13\15\0\11\13\1\242\4\13\2\0\2\13\5\0" +
                    "\5\13\3\0\3\13\6\0\2\13\15\0\3\13\1\243" +
                    "\6\13\1\244\3\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\12\13\1\245\3\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\5\13\1\246\10\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\1\13\1\247\14\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\1\13\1\250\14\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\3\13\1\251\12\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\12\13\1\252\3\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\11\13\1\253\4\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\1\254\15\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\10\13\1\255\5\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\16\13" +
                    "\2\0\2\13\5\0\4\13\1\256\3\0\3\13\6\0" +
                    "\2\13\15\0\6\13\1\257\7\13\2\0\2\13\5\0" +
                    "\5\13\3\0\3\13\5\0\12\203\1\0\66\203\1\260" +
                    "\54\203\12\261\1\262\2\261\1\263\2\261\1\264\46\261" +
                    "\12\206\1\207\2\206\1\210\65\206\1\116\1\205\51\206" +
                    "\12\265\1\266\2\265\1\210\51\265\4\206\1\267\5\206" +
                    "\1\207\2\206\1\210\3\206\1\270\44\206\1\267\12\212" +
                    "\1\271\54\212\12\0\1\213\3\0\1\205\56\0\1\205" +
                    "\61\0\2\13\15\0\11\13\1\272\4\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\6\13" +
                    "\1\273\7\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\3\13\1\274\12\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\6\13" +
                    "\1\275\7\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\11\13\1\276\2\13\1\277\1\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\11\13\1\300\4\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\1\301\15\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\14\13\1\302\1\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\1\13\1\303\14\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\6\13\1\304\7\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\7\13\1\305\6\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\6\13\1\306\7\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\1\13\1\307\14\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\6\13\1\310\7\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\10\13\1\311\5\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\6\13\1\312\7\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\7\13\1\313\6\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\2\13\1\314\13\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\14\13\1\315\1\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\16\13\2\0\2\13\5\0\1\13\1\316\3\13\3\0" +
                    "\3\13\6\0\2\13\15\0\15\13\1\317\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\3\13" +
                    "\1\320\12\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\2\13\1\321\13\13\2\0\2\13" +
                    "\5\0\4\13\1\322\3\0\3\13\6\0\2\13\15\0" +
                    "\1\323\15\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\7\13\1\324\6\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\5\0\12\203\1\260\1\203" +
                    "\1\205\52\203\12\261\1\262\2\261\1\263\63\261\1\325" +
                    "\1\261\1\205\1\203\55\261\1\326\5\261\1\262\2\261" +
                    "\1\263\3\261\1\327\44\261\1\326\14\265\2\0\51\265" +
                    "\12\206\1\207\2\206\1\210\4\206\1\330\44\206\12\212" +
                    "\1\271\3\212\1\205\50\212\1\0\2\13\15\0\1\331" +
                    "\15\13\2\0\2\13\5\0\5\13\3\0\3\13\6\0" +
                    "\2\13\15\0\12\13\1\332\3\13\2\0\2\13\5\0" +
                    "\5\13\3\0\3\13\6\0\2\13\15\0\6\13\1\333" +
                    "\7\13\2\0\2\13\5\0\5\13\3\0\3\13\6\0" +
                    "\2\13\15\0\1\334\15\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\11\13\1\335\4\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\3\13\1\336\12\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\11\13\1\337\4\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\16\13\2\0\2\13\5\0\2\13\1\340\2\13" +
                    "\3\0\3\13\6\0\2\13\15\0\12\13\1\341\3\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\7\13\1\342\6\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\3\13\1\343\12\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\11\13\1\344\4\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\6\13\1\345\7\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\7\13\1\346\6\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\6\13\1\347\7\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\6\13\1\350\7\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\12\13\1\351\3\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\1\13\1\352\14\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\16\13\2\0\2\13" +
                    "\5\0\5\13\3\0\1\13\1\353\1\13\5\0\12\261" +
                    "\1\262\1\261\1\354\1\263\63\261\1\262\2\261\1\263" +
                    "\4\261\1\355\44\261\12\206\1\207\2\206\1\210\5\206" +
                    "\1\356\43\206\1\0\2\13\15\0\7\13\1\357\6\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\16\13\2\0\2\13\5\0\1\360\4\13\3\0" +
                    "\3\13\6\0\2\13\15\0\16\13\2\0\1\13\1\361" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\1\13" +
                    "\1\362\14\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\10\13\1\363\5\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\5\13" +
                    "\1\364\10\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\11\13\1\365\4\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\1\366" +
                    "\15\13\2\0\2\13\5\0\5\13\3\0\3\13\6\0" +
                    "\2\13\15\0\1\367\15\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\12\13\1\370\3\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\5\13\1\371\10\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\7\13\1\372\6\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\5\0\12\261" +
                    "\1\262\2\261\1\263\5\261\1\373\43\261\12\206\1\207" +
                    "\2\206\1\210\6\206\1\374\42\206\1\0\2\13\15\0" +
                    "\3\13\1\375\12\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\7\13\1\376\6\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\6\13\1\377\7\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\4\13\1\u0100\11\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\16\13\2\0\2\13\5\0\5\13\3\0\2\13\1\u0101" +
                    "\6\0\2\13\15\0\10\13\1\u0102\5\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\5\13" +
                    "\1\u0103\10\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\4\13\1\u0104\11\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\16\13" +
                    "\2\0\1\13\1\u0105\5\0\5\13\3\0\3\13\5\0" +
                    "\12\261\1\262\2\261\1\263\6\261\1\u0106\42\261\12\206" +
                    "\1\207\2\206\1\210\7\206\1\u0107\41\206\1\0\2\13" +
                    "\15\0\1\u0108\15\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\2\13\1\u0109\13\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\1\13\1\u010a\14\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\6\13\1\u010b\7\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\7\13\1\u010c\6\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\6\0\2\13\15\0\1\13\1\u010d\14\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\12\13\1\u010e\3\13\2\0\2\13\5\0\5\13\3\0" +
                    "\3\13\5\0\12\261\1\262\2\261\1\263\7\261\1\u010f" +
                    "\41\261\12\206\1\207\2\206\1\210\10\206\1\267\40\206" +
                    "\1\0\2\13\15\0\16\13\2\0\2\13\5\0\5\13" +
                    "\3\0\2\13\1\u0110\6\0\2\13\15\0\6\13\1\u0111" +
                    "\7\13\2\0\2\13\5\0\5\13\3\0\3\13\6\0" +
                    "\2\13\15\0\11\13\1\u0112\4\13\2\0\2\13\5\0" +
                    "\5\13\3\0\3\13\6\0\2\13\15\0\11\13\1\u0113" +
                    "\4\13\2\0\2\13\5\0\5\13\3\0\3\13\6\0" +
                    "\2\13\15\0\6\13\1\u0114\7\13\2\0\2\13\5\0" +
                    "\5\13\3\0\3\13\5\0\12\261\1\262\2\261\1\263" +
                    "\10\261\1\326\40\261\1\0\2\13\15\0\7\13\1\u0115" +
                    "\6\13\2\0\2\13\5\0\5\13\3\0\3\13\6\0" +
                    "\2\13\15\0\7\13\1\u0116\6\13\2\0\2\13\5\0" +
                    "\5\13\3\0\3\13\6\0\2\13\15\0\1\u0117\15\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\11\13\1\u0118\4\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\11\13\1\u0119\4\13" +
                    "\2\0\2\13\5\0\5\13\3\0\3\13\6\0\2\13" +
                    "\15\0\10\13\1\u011a\5\13\2\0\2\13\5\0\5\13" +
                    "\3\0\3\13\6\0\2\13\15\0\1\u011b\15\13\2\0" +
                    "\2\13\5\0\5\13\3\0\3\13\6\0\2\13\15\0" +
                    "\1\u011c\15\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\1\13\1\u011d\14\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\10\13" +
                    "\1\u011e\5\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\10\13\1\u011f\5\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\6\0\2\13\15\0\1\13" +
                    "\1\u0120\14\13\2\0\2\13\5\0\5\13\3\0\3\13" +
                    "\6\0\2\13\15\0\1\13\1\u0121\14\13\2\0\2\13" +
                    "\5\0\5\13\3\0\3\13\5\0";
    /**
     * The transition table of the DFA
     */
    private static final int[] ZZ_TRANS = zzUnpackTrans();
    /* error codes */
    private static final int ZZ_UNKNOWN_ERROR = 0;
    private static final int ZZ_NO_MATCH = 1;
    private static final int ZZ_PUSHBACK_2BIG = 2;
    /* error messages for the codes above */
    private static final String ZZ_ERROR_MSG[] = {
            "Unkown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
    };
    private static final String ZZ_ATTRIBUTE_PACKED_0 =
            "\1\0\1\1\6\0\1\11\6\1\1\11\1\1\1\11" +
                    "\21\1\5\11\4\1\2\11\1\1\3\11\1\1\1\11" +
                    "\1\1\1\11\3\1\2\11\3\1\1\11\3\1\1\11" +
                    "\1\1\1\11\4\1\1\0\1\1\1\11\5\0\30\1" +
                    "\6\11\11\1\1\11\2\1\1\11\1\0\2\1\2\0" +
                    "\1\1\2\0\1\11\2\0\1\1\3\0\44\1\3\0" +
                    "\1\1\3\0\1\1\2\0\33\1\1\0\1\1\2\0" +
                    "\24\1\2\0\14\1\2\0\11\1\2\0\7\1\1\0" +
                    "\22\1";
    /**
     * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
     */
    private static final int[] ZZ_ATTRIBUTE = zzUnpackAttribute();
    /* user code: */
    List<ScriptSource> searchDirectories;
    Stack<String> sourcenames;
    StringBuilder literal = new StringBuilder();
    /**
     * the input device
     */
    private java.io.Reader zzReader;
    /**
     * the current state of the DFA
     */
    private int zzState;
    /**
     * the current lexical state
     */
    private int zzLexicalState = YYINITIAL;
    /**
     * this buffer contains the current text to be matched and is
     * the source of the yytext() string
     */
    private char zzBuffer[] = new char[ZZ_BUFFERSIZE];
    /**
     * the textposition at the last accepting state
     */
    private int zzMarkedPos;
    /**
     * the current text position in the buffer
     */
    private int zzCurrentPos;
    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private int zzStartRead;
    /**
     * endRead marks the last character in the buffer, that has been read
     * from input
     */
    private int zzEndRead;
    /**
     * number of newlines encountered up to the start of the matched text
     */
    private int yyline;
    /**
     * the number of characters up to the start of the matched text
     */
    private int yychar;
    /**
     * the number of characters from the last newline up to the start of the
     * matched text
     */
    private int yycolumn;
    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private boolean zzAtBOL = true;
    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private boolean zzAtEOF;
    /**
     * denotes if the user-EOF-code has already been executed
     */
    private boolean zzEOFDone;
    private Stack zzStreams = new Stack();
    private String tmpname;
    private Reader tmpreader;

    /**
     * Creates a new scanner
     * There is also a java.io.InputStream version of this constructor.
     *
     * @param in the java.io.Reader to read input from.
     */
    Lexer(java.io.Reader in, String sourcename, List<ScriptSource> searchDirectories) {
        sourcenames = new Stack<String>();
        sourcenames.push(sourcename);
        this.searchDirectories = searchDirectories;
        this.zzReader = in;
    }

    /**
     * Creates a new scanner.
     * There is also java.io.Reader version of this constructor.
     *
     * @param in the java.io.Inputstream to read input from.
     */
    Lexer(java.io.InputStream in, String sourcename, List<ScriptSource> searchDirectories) {
        this(new java.io.InputStreamReader(in), sourcename, searchDirectories);
    }

    private static int[] zzUnpackAction() {
        int[] result = new int[289];
        int offset = 0;
        offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAction(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    private static int[] zzUnpackRowMap() {
        int[] result = new int[289];
        int offset = 0;
        offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackRowMap(String packed, int offset, int[] result) {
        int i = 0;  /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int high = packed.charAt(i++) << 16;
            result[j++] = high | packed.charAt(i++);
        }
        return j;
    }

    private static int[] zzUnpackTrans() {
        int[] result = new int[11220];
        int offset = 0;
        offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackTrans(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            value--;
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    private static int[] zzUnpackAttribute() {
        int[] result = new int[289];
        int offset = 0;
        offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
        return result;
    }

    private static int zzUnpackAttribute(String packed, int offset, int[] result) {
        int i = 0;       /* index in packed string  */
        int j = offset;  /* index in unpacked array */
        int l = packed.length();
        while (i < l) {
            int count = packed.charAt(i++);
            int value = packed.charAt(i++);
            do result[j++] = value; while (--count > 0);
        }
        return j;
    }

    /**
     * Unpacks the compressed character translation table.
     *
     * @param packed the packed character translation table
     * @return the unpacked character translation table
     */
    private static char[] zzUnpackCMap(String packed) {
        char[] map = new char[0x10000];
        int i = 0;  /* index in packed string  */
        int j = 0;  /* index in unpacked array */
        while (i < 182) {
            int count = packed.charAt(i++);
            char value = packed.charAt(i++);
            do map[j++] = value; while (--count > 0);
        }
        return map;
    }

    void addInclude(String name) throws FileNotFoundException {
        for (ScriptSource s : searchDirectories) {
            Reader r = s.read(name);
            if (r != null) {
                this.tmpreader = r;
                this.tmpname = name;
                return;
            }
        }
        throw new FileNotFoundException("Cannot find the $INCLUDE file " + name);
    }

    void commitInclude() {
        sourcenames.push(tmpname);
        yypushStream(tmpreader);
    }

    public final boolean yymoreStreams() {
        return !zzStreams.isEmpty();
    }

    public final void yypopStream() throws java.io.IOException {
        zzReader.close();
        ZzFlexStreamInfo s = (ZzFlexStreamInfo) zzStreams.pop();
        zzBuffer = s.zzBuffer;
        zzReader = s.zzReader;
        zzEndRead = s.zzEndRead;
        zzStartRead = s.zzStartRead;
        zzCurrentPos = s.zzCurrentPos;
        zzMarkedPos = s.zzMarkedPos;
        zzAtEOF = s.zzAtEOF;
        zzEOFDone = s.zzEOFDone;
        yyline = s.yyline;
        yycolumn = s.yycolumn;
    }

    public final void yypushStream(Reader reader) {
        zzStreams.push(
                new ZzFlexStreamInfo(zzReader, zzEndRead, zzStartRead, zzCurrentPos,
                        zzMarkedPos, zzBuffer, zzAtEOF,
                        yyline, yycolumn)
        );
        zzAtEOF = false;
        zzBuffer = new char[ZZ_BUFFERSIZE];
        zzReader = reader;
        zzEndRead = zzStartRead = 0;
        zzCurrentPos = zzMarkedPos = 0;
        yyline = yycolumn = 0;
    }

    LineInfo getLine() {
        return new LineInfo(yyline, yycolumn, sourcenames.peek());
    }

    /**
     * Refills the input buffer.
     *
     * @return <code>false</code>, iff there was new input.
     * @throws java.io.IOException if any I/O-Error occurs
     */
    private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
        if (zzStartRead > 0) {
            System.arraycopy(zzBuffer, zzStartRead,
                    zzBuffer, 0,
                    zzEndRead - zzStartRead);

      /* translate stored positions */
            zzEndRead -= zzStartRead;
            zzCurrentPos -= zzStartRead;
            zzMarkedPos -= zzStartRead;
            zzStartRead = 0;
        }

    /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
            char newBuffer[] = new char[zzCurrentPos * 2];
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
            zzBuffer = newBuffer;
        }

    /* finally: fill the buffer with new input */
        int numRead = zzReader.read(zzBuffer, zzEndRead,
                zzBuffer.length - zzEndRead);

        if (numRead > 0) {
            zzEndRead += numRead;
            return false;
        }
        // unlikely but not impossible: read 0 characters, but not at end of stream
        if (numRead == 0) {
            int c = zzReader.read();
            if (c == -1) {
                return true;
            } else {
                zzBuffer[zzEndRead++] = (char) c;
                return false;
            }
        }

        // numRead < 0
        return true;
    }


    /**
     * Closes the input stream.
     */
    public final void yyclose() throws java.io.IOException {
        zzAtEOF = true;            /* indicate end of file */
        zzEndRead = zzStartRead;  /* invalidate buffer    */

        if (zzReader != null)
            zzReader.close();
    }


    /**
     * Resets the scanner to read from a new input stream.
     * Does not close the old reader.
     * <p>
     * All internal variables are reset, the old input stream
     * <b>cannot</b> be reused (internal buffer is discarded and lost).
     * Lexical state is set to <tt>ZZ_INITIAL</tt>.
     *
     * @param reader the new input stream
     */
    public final void yyreset(java.io.Reader reader) {
        zzReader = reader;
        zzAtBOL = true;
        zzAtEOF = false;
        zzEOFDone = false;
        zzEndRead = zzStartRead = 0;
        zzCurrentPos = zzMarkedPos = 0;
        yyline = yychar = yycolumn = 0;
        zzLexicalState = YYINITIAL;
    }


    /**
     * Returns the current lexical state.
     */
    public final int yystate() {
        return zzLexicalState;
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    public final void yybegin(int newState) {
        zzLexicalState = newState;
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    public final String yytext() {
        return new String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead);
    }


    /**
     * Returns the character at position <tt>pos</tt> from the
     * matched text.
     * <p>
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     *            A value from 0 to yylength()-1.
     * @return the character at position pos
     */
    public final char yycharat(int pos) {
        return zzBuffer[zzStartRead + pos];
    }


    /**
     * Returns the length of the matched text region.
     */
    public final int yylength() {
        return zzMarkedPos - zzStartRead;
    }


    /**
     * Reports an error that occured while scanning.
     * <p>
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     * <p>
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private void zzScanError(int errorCode) {
        String message;
        try {
            message = ZZ_ERROR_MSG[errorCode];
        } catch (ArrayIndexOutOfBoundsException e) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
        }

        throw new Error(message);
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     * <p>
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again.
     *               This number must not be greater than yylength()!
     */
    public void yypushback(int number) {
        if (number > yylength())
            zzScanError(ZZ_PUSHBACK_2BIG);

        zzMarkedPos -= number;
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @throws java.io.IOException if any I/O-Error occurs
     */
    public Token yylex() throws java.io.IOException {
        int zzInput;
        int zzAction;

        // cached fields:
        int zzCurrentPosL;
        int zzMarkedPosL;
        int zzEndReadL = zzEndRead;
        char[] zzBufferL = zzBuffer;
        char[] zzCMapL = ZZ_CMAP;

        int[] zzTransL = ZZ_TRANS;
        int[] zzRowMapL = ZZ_ROWMAP;
        int[] zzAttrL = ZZ_ATTRIBUTE;

        while (true) {
            zzMarkedPosL = zzMarkedPos;

            boolean zzR = false;
            for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                 zzCurrentPosL++) {
                switch (zzBufferL[zzCurrentPosL]) {
                    case '\u000B':
                    case '\u000C':
                    case '\u0085':
                    case '\u2028':
                    case '\u2029':
                        yyline++;
                        yycolumn = 0;
                        zzR = false;
                        break;
                    case '\r':
                        yyline++;
                        yycolumn = 0;
                        zzR = true;
                        break;
                    case '\n':
                        if (zzR)
                            zzR = false;
                        else {
                            yyline++;
                            yycolumn = 0;
                        }
                        break;
                    default:
                        zzR = false;
                        yycolumn++;
                }
            }

            if (zzR) {
                // peek one character ahead if it is \n (if we have counted one line too much)
                boolean zzPeek;
                if (zzMarkedPosL < zzEndReadL)
                    zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                else if (zzAtEOF)
                    zzPeek = false;
                else {
                    boolean eof = zzRefill();
                    zzEndReadL = zzEndRead;
                    zzMarkedPosL = zzMarkedPos;
                    zzBufferL = zzBuffer;
                    if (eof)
                        zzPeek = false;
                    else
                        zzPeek = zzBufferL[zzMarkedPosL] == '\n';
                }
                if (zzPeek) yyline--;
            }
            zzAction = -1;

            zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

            zzState = ZZ_LEXSTATE[zzLexicalState];


            zzForAction:
            {
                while (true) {

                    if (zzCurrentPosL < zzEndReadL)
                        zzInput = zzBufferL[zzCurrentPosL++];
                    else if (zzAtEOF) {
                        zzInput = YYEOF;
                        break zzForAction;
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL;
                        zzMarkedPos = zzMarkedPosL;
                        boolean eof = zzRefill();
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos;
                        zzMarkedPosL = zzMarkedPos;
                        zzBufferL = zzBuffer;
                        zzEndReadL = zzEndRead;
                        if (eof) {
                            zzInput = YYEOF;
                            break zzForAction;
                        } else {
                            zzInput = zzBufferL[zzCurrentPosL++];
                        }
                    }
                    int zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput]];
                    if (zzNext == -1) break zzForAction;
                    zzState = zzNext;

                    int zzAttributes = zzAttrL[zzState];
                    if ((zzAttributes & 1) == 1) {
                        zzAction = zzState;
                        zzMarkedPosL = zzCurrentPosL;
                        if ((zzAttributes & 8) == 8) break zzForAction;
                    }

                }
            }

            // store back cached position
            zzMarkedPos = zzMarkedPosL;

            switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
                case 16: {
                    return new OperatorToken(getLine(), OperatorTypes.ADDRESS);
                }
                case 97:
                    break;
                case 65: {
                    return new SetToken(getLine());
                }
                case 98:
                    break;
                case 71: {
                    return new UnitToken(getLine());
                }
                case 99:
                    break;
                case 26: {
                    yypushback(1);
                    yybegin(YYINITIAL);
                    if (literal.length() == 1) {
                        return new CharacterToken(getLine(), literal.toString().charAt(0));
                        //return new CharacterToken(getLine(),literal.toString());
                    } else {
                        LineInfo lineInfo = getLine();
                        lineInfo.column = lineInfo.column - literal.length();
                        return new StringToken(lineInfo, literal.toString());
                    }
                }
                case 100:
                    break;
                case 22: {
                    return new EndBracketToken(getLine());
                }
                case 101:
                    break;
                case 9: {
                    return new EndParenToken(getLine());
                }
                case 102:
                    break;
                case 36: {
                    return new GroupingExceptionToken(getLine(),
                            GroupingExceptionType.GroupExceptionType.NEWLINE_IN_QUOTES);
                }
                case 103:
                    break;
                case 33: {
                    literal.setLength(0);
                    yybegin(INCLUDE_DBL_QUOTE);
                }
                case 104:
                    break;
                case 76: {
                    return new TypeToken(getLine());
                }
                case 105:
                    break;
                case 79: {
                    return new UntilToken(getLine());
                }
                case 106:
                    break;
                case 95: {
                    return new InitializationToken(getLine());
                }
                case 107:
                    break;
                case 2: {
                    return new GroupingExceptionToken(new StrayCharacterException(getLine(), yytext().charAt(0)));
                }
                case 108:
                    break;
                case 43: {
                    return new IfToken(getLine());
                }
                case 109:
                    break;
                case 63: {
                    return new OperatorToken(getLine(), OperatorTypes.AND);
                }
                case 110:
                    break;
                case 81: {
                    return new BooleanToken(getLine(), false);
                }
                case 111:
                    break;
                case 84: {
                    return new BreakToken(getLine());
                }
                case 112:
                    break;
                case 93: {
                    return new ProcedureToken(getLine());
                }
                case 113:
                    break;
                case 7: {
                    return new ParenthesizedToken(getLine());
                }
                case 114:
                    break;
                case 23: {
                    literal.setLength(0);
                    yybegin(STRING);
                }
                case 115:
                    break;
                case 60: {
                    return new OperatorToken(getLine(), OperatorTypes.NOT);
                }
                case 116:
                    break;
                case 85: {
                    return new DowntoToken(getLine());
                }
                case 117:
                    break;
                case 52: {
                    return new OperatorToken(getLine(), OperatorTypes.SHIFTRIGHT);
                }
                case 118:
                    break;
                case 49: {
                    return new OperatorToken(getLine(), OperatorTypes.NOTEQUAL);
                }
                case 119:
                    break;
                case 19: {
                    return new CommaToken(getLine());
                }
                case 120:
                    break;
                case 20: {
                    return new SemicolonToken(getLine());
                }
                case 121:
                    break;
                case 68: {
                    return new ForToken(getLine());
                }
                case 122:
                    break;
                case 80: {
                    return new ArrayToken(getLine());
                }
                case 123:
                    break;
                case 92: {
                    return new InterfaceToken(getLine());
                }
                case 124:
                    break;
                case 34: {
                    return new GroupingExceptionToken(getLine(),
                            GroupingExceptionType.GroupExceptionType.IO_EXCEPTION);
                }
                case 125:
                    break;
                case 14: {
                    return new OperatorToken(getLine(), OperatorTypes.PLUS);
                }
                case 126:
                    break;
                case 54: {
                    return new AssignmentToken(getLine());
                }
                case 127:
                    break;
                case 25: {
                    yybegin(STRINGDONE);
                }
                case 128:
                    break;
                case 11: {
                    return new OperatorToken(getLine(), OperatorTypes.LESSTHAN);
                }
                case 129:
                    break;
                case 94: {
                    return new FinalizationToken(getLine());
                }
                case 130:
                    break;
                case 32: {
                    literal.setLength(0);
                    yybegin(INCLUDE_SNGL_QUOTE);
                }
                case 131:
                    break;
                case 64: {
                    return new OperatorToken(getLine(), OperatorTypes.XOR);
                }
                case 132:
                    break;
                case 58: {
                    return new CommentToken(getLine(), yytext());
                }
                case 133:
                    break;
                case 6: {
                    return new PeriodToken(getLine());
                }
                case 134:
                    break;
                case 4: {
                    return new WordToken(getLine(), yytext());
                }
                case 135:
                    break;
                case 12: {
                    return new OperatorToken(getLine(), OperatorTypes.GREATERTHAN);
                }
                case 136:
                    break;
                case 28: {
                    return new GroupingExceptionToken(getLine(), GroupingExceptionType.GroupExceptionType.INCOMPLETE_CHAR);
                }
                case 137:
                    break;
                case 62: {
                    return new EndToken(getLine());
                }
                case 138:
                    break;
                case 50: {
                    return new OperatorToken(getLine(), OperatorTypes.LESSEQ);
                }
                case 139:
                    break;
                case 90: {
                    return new ContinueToken(getLine());
                }
                case 140:
                    break;
                case 74: {
                    return new BooleanToken(getLine(), true);
                }
                case 141:
                    break;
                case 96: {
                    return new ImplementationToken(getLine());
                }
                case 142:
                    break;
                case 41: {
                    return new DotDotToken(getLine());
                }
                case 143:
                    break;
                case 91: {
                    return new FunctionToken(getLine());
                }
                case 144:
                    break;
                case 1: {
                    literal.append(yytext());
                }
                case 145:
                    break;
                case 24: {
                    return new GroupingExceptionToken(getLine(), GroupingExceptionType.GroupExceptionType.NEWLINE_IN_QUOTES);
                }
                case 146:
                    break;
                case 70: {
                    return new CaseToken(getLine());
                }
                case 147:
                    break;
                case 75: {
                    return new ThenToken(getLine());
                }
                case 148:
                    break;
                case 42: {
                    return new OperatorToken(getLine(), OperatorTypes.IN);
                }
                case 149:
                    break;
                case 78: {
                    return new ConstToken(getLine());
                }
                case 150:
                    break;
                case 38: {
                    return new GroupingExceptionToken(getLine(),
                            GroupingExceptionType.GroupExceptionType.MISMATCHED_BRACKETS);
                }
                case 151:
                    break;
                case 45: {
                    return new OperatorToken(getLine(), OperatorTypes.OR);
                }
                case 152:
                    break;
                case 69: {
                    yybegin(INCLUDE);
                }
                case 153:
                    break;
                case 89: {
                    return new ProgramToken(getLine());
                }
                case 154:
                    break;
                case 15: {
                    return new OperatorToken(getLine(), OperatorTypes.MINUS);
                }
                case 155:
                    break;
                case 40: {
                    return new CharacterToken(getLine(), yytext());
                }
                case 156:
                    break;
                case 8: {
                    return new OperatorToken(getLine(), OperatorTypes.MULTIPLY);
                }
                case 157:
                    break;
                case 46: {
                    return new OfToken(getLine());
                }
                case 158:
                    break;
                case 59: {
                    return new WarningToken(getLine(), "Warning! Unrecognized Compiler Directive!");
                }
                case 159:
                    break;
                case 27: {
                    yybegin(STRING);
                }
                case 160:
                    break;
                case 53: {
                    return new OperatorToken(getLine(), OperatorTypes.GREATEREQ);
                }
                case 161:
                    break;
                case 66: {
                    return new VarToken(getLine());
                }
                case 162:
                    break;
                case 21: {
                    return new BracketedToken(getLine());
                }
                case 163:
                    break;
                case 10: {
                    return new OperatorToken(getLine(), OperatorTypes.DIVIDE);
                }
                case 164:
                    break;
                case 35: {
                    try {
                        addInclude(yytext());
                    } catch (FileNotFoundException e) {
                        GroupingExceptionType t = new GroupingExceptionType(getLine(),
                                GroupingExceptionType.GroupExceptionType.IO_EXCEPTION);
                        t.caused = e;
                        return new GroupingExceptionToken(t);
                    }
                    yybegin(END_INCLUDE);
                }
                case 165:
                    break;
                case 47: {
                    return new ToToken(getLine());
                }
                case 166:
                    break;
                case 37: {
                    try {
                        addInclude(yytext());
                    } catch (FileNotFoundException e) {
                        GroupingExceptionType t = new GroupingExceptionType(getLine(),
                                GroupingExceptionType.GroupExceptionType.IO_EXCEPTION);
                        t.caused = e;
                        return new GroupingExceptionToken(t);
                    }
                    yybegin(END_INCLUDE);
                }
                case 167:
                    break;
                case 88: {
                    return new ForwardToken(getLine());
                }
                case 168:
                    break;
                case 83: {
                    return new BeginEndToken(getLine());
                }
                case 169:
                    break;
                case 44: {
                    return new DoToken(getLine());
                }
                case 170:
                    break;
                case 18: {
                    return new ColonToken(getLine());
                }
                case 171:
                    break;
                case 56: {
                    literal.append('\"');
                }
                case 172:
                    break;
                case 57: {
                    return new DoubleToken(getLine(), Double.parseDouble(yytext()));
                }
                case 173:
                    break;
                case 77: {
                    return new WithToken(getLine());
                }
                case 174:
                    break;
                case 73: {
                    return new ElseToken(getLine());
                }
                case 175:
                    break;
                case 31: {
                    return new GroupingExceptionToken(getLine(),
                            GroupingExceptionType.GroupExceptionType.MISSING_INCLUDE);
                }
                case 176:
                    break;
                case 29: {
                    literal.append((char) Integer.parseInt(yytext()));
                    yybegin(STRINGDONE);
                }
                case 177:
                    break;
                case 72: {
                    return new UsesToken(getLine());
                }
                case 178:
                    break;
                case 86: {
                    return new RecordToken(getLine());
                }
                case 179:
                    break;
                case 82: {
                    return new WhileToken(getLine());
                }
                case 180:
                    break;
                case 17: {
                    return new OperatorToken(getLine(), OperatorTypes.DEREF);
                }
                case 181:
                    break;
                case 61: {
                    return new OperatorToken(getLine(), OperatorTypes.DIV);
                }
                case 182:
                    break;
                case 3: {
                    return new IntegerToken(getLine(), (int) Long.parseLong(yytext()));
                }
                case 183:
                    break;
                case 13: {
                    return new OperatorToken(getLine(), OperatorTypes.EQUALS);
                }
                case 184:
                    break;
                case 48: {
                    return new OperatorToken(getLine(), OperatorTypes.SHIFTLEFT);
                }
                case 185:
                    break;
                case 87: {
                    return new RepeatToken(getLine());
                }
                case 186:
                    break;
                case 67: {
                    return new OperatorToken(getLine(), OperatorTypes.MOD);
                }
                case 187:
                    break;
                case 51: {
                    return new OperatorToken(getLine(), OperatorTypes.DIFFERENT);
                }
                case 188:
                    break;
                case 39: {
                    yybegin(YYINITIAL);
                    commitInclude();
                }
                case 189:
                    break;
                case 30: {
                    try {
                        addInclude(yytext());
                    } catch (FileNotFoundException e) {
                        GroupingExceptionType t = new GroupingExceptionType(getLine(),
                                GroupingExceptionType.GroupExceptionType.IO_EXCEPTION);
                        t.caused = e;
                        return new GroupingExceptionToken(t);
                    }
                    yybegin(END_INCLUDE);
                }
                case 190:
                    break;
                case 55: {
                    literal.append('\'');
                }
                case 191:
                    break;
                case 5: {
                }
                case 192:
                    break;
                default:
                    if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                        zzAtEOF = true;
                        {
                            if (!yymoreStreams()) {
                                return new EOFToken(getLine());
                            }
                            sourcenames.pop();
                            yypopStream();
                        }
                    } else {
                        zzScanError(ZZ_NO_MATCH);
                    }
            }
        }
    }


}
